# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_images_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
    ]
